DROP TABLE IF EXISTS ORDERLINE;
DROP TABLE IF EXISTS RESTAURANT_TABLE;
DROP TABLE IF EXISTS INCLUDE;
DROP TABLE IF EXISTS TOURIST_LANGUAGE;

DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS MENUITEM;
DROP TABLE IF EXISTS COUPON;

DROP TABLE IF EXISTS TOURISTDISCOUNT;
DROP TABLE IF EXISTS TOURIST;
DROP TABLE IF EXISTS SERVICEPROVIDER;